pipeline {
    agent any

    stages{
        stage('SCM') {
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/FeynmanFan/getting-started-jenkins']])
            }
        }
        stage('Compile') {
            steps{
                dotnetBuild project: 'gsj.sln'
            }
        }
        stage('Test') {
            steps{
                bat 'dotnet test gsj.sln'
            }
        }
        stage('Archive')
        {
            echo 'Archive the results of the build'
        }
        stage('Cleanup'){
            cleanWs()
        }
    }
}